### PR TITLE
Several (other) updates

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
Sorry for not including these updates in the last PR.
Can you please have a look before I adjust the version number and the checksum?

There is a new suggestion (`||static*.*/servev*/*.gif$image`) that might make other rules redundant, and thus duplicates. (however, maybe `.gif` should not be used.)

There also needs to be another PR for some other mainstream persian websites that I've collected, but these seemed to have more priority.

### CODE REVIEW

**Comment by farrokhi** [comment]
> There is a new suggestion (`||static*.*/servev*/*.gif$image`) that might make other rules redundant, and thus duplicates. (however, maybe `.gif` should not be used.)

This will be unnecessarily too expensive. I understand that several sites use similar frameworks and this might simplify the blocking rules, but from a user perspective, wildcard matching on sites would impact browser performance.
Let's move forward on a site-by-site basis.

**Comment by farrokhi** [comment]
LGTM. Please bump up version and update checksum.

**Comment by DRSDavidSoft** [comment]
> This will be unnecessarily too expensive. I understand that several sites use similar frameworks and this might simplify the blocking rules, but from a user perspective, wildcard matching on sites would impact browser performance.
Let's move forward on a site-by-site basis.

I understand, and I agree with the points. Will be happy to add domains on a site-by-site basis 😄 

Ready to merge?

**Comment by farrokhi** [comment]
Thanks!

**Pull request merged**
